# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5436/airline_ops
spring.datasource.username=library_user
spring.datasource.password=library_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - importante: validate para que no modifique tus tablas
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=library
spring.jpa.show-sql=true

# Puerto del servidor
server.port=8080